### ISSUE TITLE
This version of Terraform has an outdated GPG key

### ISSUE THREAD

**Issue by gruberdev** [jckuester/awsrm#1]
## Issue:
I followed the instructions as per the README on how to install the project's binary file, proceeding to place it on my `$PATH`, returning this following error afterward:

## Full logs:
```sh
sh awsls vpc -a tags  | grep Name=vpc | awsrm                                                 

failed to install provider (aws): 2 problems:
- registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
- open ~/.awsrm/terraform-provider-aws_v3.16.0_x5: text file busy
Error: failed to launch provider (): fork/exec : no such file or directory
```

This bug seems to refer to [this thread on Hashicorp's forums](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512)

Something curious to be noted is that my machine's Terraform is at v15.x already. So it might have something to do with the project dependencies. 

All the best.

**Comment by jckuester** [comment]
Thanks @gruberdev for opening the issue. I'll update awsrm to the newest Terraform AWS Provider version and let you know when done.

**Comment by jckuester** [comment]
Hi @gruberdev again, I switched to a newer Terraform AWS Provider in https://github.com/jckuester/awsrm/releases/tag/v0.2.0. Let me know if `awsrm` works for you know. Thanks!

**Comment by gruberdev** [comment]
> 
> 
> Hi @gruberdev again, I switched to a newer Terraform AWS Provider in [v0.2.0](https://github.com/jckuester/awsrm/releases/tag/v0.2.0). Let me know if `awsrm` works for you now. Thanks!

I will test soon enough in a clean environment to report back to you, thanks for keeping my updated!

**Comment by gruberdev** [comment]
It worked perfectly, thanks @jckuester!
