### ISSUE TITLE
Introduce --force flag

### ISSUE THREAD

**Issue by Veetaha** [jckuester/awsrm#4]
I suggest adding a `--force` flag to the CLI so that when `awsrm` is run in automation no confirmation is required from the calling process.

Btw, if the calling process tries to work around this by setting a pipe and writing `Yes` to it, this doesn't work because `awsrm` expects the resources passed in a special format when it is invoked via a pipe

**Comment by andreamaruccia** [comment]
+1, cannot really use it in automation scripts without this

**Comment by christonog** [comment]
I have a local branch which introduces this feature, but I can't seem to push it to create a PR. @jckuester Would it be possible to open up the project to allow contributions?

**Comment by jckuester** [comment]
@christonog can you fork my repo and then open the PR from your fork against my repo, please? Thanks for the PR in advance :)

**Comment by christonog** [comment]
Ah I see now, thanks @jckuester! I've created the PR: https://github.com/jckuester/awsrm/pull/6 Hopefully I created it correctly! I appreciate your feedback!

**Comment by Veetaha** [comment]
Thank you guys, the `--force` flag is dope, I am closing this issue, because #6 has resolved it and `0.3.0` is already released!
